Consegna progettini
lucaderi/sgr pull request #173
Opened 2021-06-02 17:15 UTC by AlecSadler

Salve, come concordato per email ho realizzato un piccolo tool di monitoraggio risorse che comprende un sistema di alert via Telegram bot.
Ho consegnato due varianti del programma, una compatibile con architettura ARM per raspberry e una compatibile con i normali computer.
Spero di non aver fatto confusione con la pull request dato che è la prima volta.

Cordialmente
Salvo Firera

2021-06-05 11:15 UTC, lucaderi requested changes
Che cosa sono i files Analytics/ram e Analytics/hdd e perche' fanno parte della consegna?

Ti prego di sistemare quanto richiesto e inserire nella relazione anche istruzioni su come installare, configurare ed eseguire il programma e non solo s[iegare cosa fa

2021-06-05 11:15 UTC, lucaderi commented on 2021/Firera/sysMonitor_PC/alert_tasks
> +	token: "1837225355:AAGMAngYknkagG6hbeZAeK8XyYApoQcjT7c",
Non devi inserire queste informazioni in una commit pubblica

2021-06-05 11:15 UTC, lucaderi commented on 2021/Firera/sysMonitor_PC/alert_tasks
> +	token: "1837225355:AAGMAngYknkagG6hbeZAeK8XyYApoQcjT7c",
Da rimuovere e mettere in una variabile

2021-06-06 08:57 UTC, AlecSadler commented
Buongiorno, i file contenuti nella directory Analytics erano solo a scopo dimostrativo, la directory viene creata dall'esecuzione della versione per raspberry, l'ho eliminata.
Per quanto riguarda gli altri punti ho ho fatto un nuovo commit in cui tolto dagli script i dati sensibili sul bot e separato i parametri del bucket di influxdb2 in un file separato (conf.py) che va modificato in base ai dati forniti dalla UI web. Come richiesto ho anche aggiornato le relazioni dettagliando tutte le operazioni, comprese quelle preliminari, da eseguire per provare il programma.

2021-06-08 20:32 UTC, lucaderi requested changes
Migliorare la gestione del numero di cores e il README e poi il progetto e' pronto per la consegna

2021-06-08 20:32 UTC, lucaderi commented on 2021/Firera/System_monitor_Raspberry/sysMonitor_ARM.py
> +                        'cpuUsage_C1' : int(session.get(OID_CPU_USAGE+'.196608').value),
Cosa sono questi valori hardcoded? Andrebbero resi parametrici e indipendenti da una CPU specifica come in questo esempio

2021-06-08 20:32 UTC, lucaderi commented on 2021/Firera/README.md
> +Dipendenze: easysnmp, matplotlib(solo versione raspberry), Inflixdb-client.
Magari aggiungere due righe che cosi' e' un po' troppo coincisa.

2021-06-10 19:58 UTC, AlecSadler commented
Salve, per rendere il programma indipendente dalla cpu specifica ho considerato la media del carico dei diversi core (ho visto che lavorano all'incirca allo stesso carico), inoltre ho riformulato il readme per renderlo più completo ed esplicativo, oltre ad averlo reso più leggibile esteticamente.

2021-06-11 14:56 UTC, lucaderi requested changes
Ultima modifica e poi il progetto va bene

2021-06-11 14:56 UTC, lucaderi commented on 2021/Firera/sysMonitor_PC/conf.py
> +INFLUXDB_TOKEN = 'Sjw-tnzb3mKiRoQMfSEi_3pjT7Q2ewL3SUSNStqBJX0WtjP5RsPuLXl75iJXIrVQ7FYX_RijAGI2zxhslPKtQA=='
Togli per favore questo valore anche se capisco ci sono poche probabilità che ce ne siano due identici? Ogni credenziale non deve essere committata in git

2021-06-11 17:16 UTC, AlecSadler commented
campi conf.py ripuliti

2021-06-15 17:28 UTC, merged