Aggiunto progetto Ramacciotti
lucaderi/sgr pull request #174
Opened 2021-06-08 12:28 UTC by 0xfederama

2021-06-08 20:24 UTC, lucaderi requested changes
Modificare quanto richiesto nella PR

2021-06-08 20:24 UTC, lucaderi commented on 2021/Ramacciotti/main.py
> +        host = 'localhost'
Rendere questi parametri configurabili come gli altri

2021-06-08 21:27 UTC, 0xfederama commented
Ho modificato quelle variabili inserendo un file di config e adattato il README

2021-06-11 12:42 UTC, lucaderi commented on 2021/Ramacciotti/main.py
> +            query = ['sysUpTimeInstance', 'ifInOctets.2', 'ifOutOctets.2', 'hrSystem.0']
Mi sono accorto che anche qui hai cablato l'indice delle interfacce di rete

2021-06-11 12:43 UTC, merged