Consegna relazione esercizio d'esame 2021
lucaderi/sgr pull request #202
Opened 2021-08-27 11:38 UTC by GabrieleMasciotti

2021-08-29 22:53 UTC, lucaderi reviewed
Le immagini 9 e 12 sono sbagliate in quanto sono state disegnate come counter piuttosto che gauge: va sistemata la configurazione di zabbix.

2021-08-29 22:54 UTC, lucaderi commented
La relazione non spiega come deve essere effettuata l'installazione, ne' i passi percorsi per riprodurre i risultati descritti nella relazione

2021-08-29 22:56 UTC, lucaderi requested changes
Sistemare i problemi riscontrati e inviare di nuovo la relazione tramite Pull Request

2021-08-30 11:00 UTC, GabrieleMasciotti commented
> Le immagini 9 e 12 sono sbagliate in quanto sono state disegnate come counter piuttosto che gauge: va sistemata la configurazione di zabbix.

Non capisco la richiesta. I grafici 9 e 12 sono stati creati appositamente per mostrare come, nei periodi di down degli agent snmp, non vengano raccolti dei valori (sempre crescenti) dei contatori di byte (RFC1213-MIB::ifInOctets.1 = Counter32), provocando dei gap di informazioni (mancanti) visibili nel grafico. Per gauge intende forse creare un grafico che riporti quanto, in ogni intervallo di misurazione, vari il numero di bytes in ingresso nell'interfaccia di rete?

2021-08-30 11:00 UTC, GabrieleMasciotti commented
Per quanto riguarda le altre richieste, provvedo subito ad effettuare le modifiche richiesta

2021-08-31 19:56 UTC, lucaderi commented
I grafici sono sbagliato perche' non possono aumentare all'infinito, il che vuol dire che hai confuso gauge con counter

2021-09-01 08:56 UTC, GabrieleMasciotti commented
Il fatto è che zabbix presenta il grafico riportando minuto per minuto il valore del contatore di rete, interrogando l'agent snmp remoto. La cosa che forse non ho detto è che il contatore non viene resettato quando l'agente va down e poi torna disponibile. Quindi il grafico riporta la crescita del valore del contatore giorno dopo giorno fin quando non viene resettato; ad esempio, in questo momento il valore che leggo dalla shell eseguendo il comando " snmpget -v 2c -c public 38.111.46.103 RFC1213-MIB::ifInOctets.2 " è 1297392508 ed infatti il grafico riporta proprio questo come ultimo valore del contatore (vedere l'immagine allegata).
![Schermata da 2021-09-01 10-53-34](https://user-images.githubusercontent.com/79256586/131642684-b7872ad4-9ca6-48c0-85f3-4bbd3192eed2.png)

2021-09-05 13:06 UTC, lucaderi commented
> Il fatto è che zabbix presenta il grafico riportando minuto per minuto il valore del contatore di rete, interrogando l'agent snmp remoto. La cosa che forse non ho detto è che il contatore non viene resettato quando l'agente va down e poi torna disponibile. Quindi il grafico riporta la crescita del valore del contatore giorno dopo giorno fin quando non viene resettato; ad esempio, in questo momento il valore che leggo dalla shell eseguendo il comando " snmpget -v 2c -c public 38.111.46.103 RFC1213-MIB::ifInOctets.2 " è 1297392508 ed infatti il grafico riporta proprio questo come ultimo valore del contatore (vedere l'immagine allegata).
> ![Schermata da 2021-09-01 10-53-34](https://user-images.githubusercontent.com/79256586/131642684-b7872ad4-9ca6-48c0-85f3-4bbd3192eed2.png)

Questo grafico e' sbagliato. Devi riportare la differenza tra due letture e non il lavoro assoluto.

2021-09-06 14:52 UTC, GabrieleMasciotti commented
Ho completato le modifiche richieste.
Mi faccia sapere se è soddisfatto o se ci sono da fare ulteriori cambiamenti/aggiunte.

2021-09-17 13:08 UTC, merged