Create MIlano-Pacini
lucaderi/sgr pull request #340
Opened 2024-10-01 20:17 UTC by xAle00

2024-10-01 20:23 UTC, lucaderi requested changes
Dovete sistemare i problemi rilevati, aggiungere un README e far leggere i parametri da linea di comando inclusa la cartella dove sono memorizzati i files di log da leggere in ordine cronologico/di nome

2024-10-01 20:23 UTC, lucaderi commented on 2024/MIlano-Pacini
> +# get per verificare se l'ip è situtato in italia
Controllo non richiesto che va tolto

2024-10-01 20:23 UTC, lucaderi commented on 2024/MIlano-Pacini
> +        response = requests.get(f"https://ipinfo.io/{ip}/json")
una richiesta per riga di log e' da evitare

2024-10-01 20:23 UTC, lucaderi commented on 2024/MIlano-Pacini
> +with open("www.ntop.org-access.log.13", "r") as file:
Dovete leggere i files di log da una cartella in ordine cronologico/di nome e NON va mai cablato niente nel codice

2024-11-13 13:52 UTC, xAle00 commented
[README.md](https://github.com/user-attachments/files/17733521/README.1.md)

2024-11-13 13:53 UTC, xAle00 commented
[README (1).md](https://github.com/user-attachments/files/17733523/README.1.md)

2024-12-04 13:28 UTC, merged